core/urls.py
from django.urls import path
from django.conf.urls import include
from core import views
# Create your views here.
app_name = "core"

urlpatterns = [
    path("", views.welcome, name="welcome"),
    path("welcome/", views.welcome, name="welcome"),
    path("home", views.home, name="home"),

    path("components/core/gmm-core/gmm-core-template", views.gmm_core_view, name="gmm_core_view"),
]

gladiatorus_server/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    
    ### --- Core --- ###
    path("", include("core.urls")),
    
    ### --- Users --- ###
    path("users/", include("users.urls")),
    path('users/friend/', include('users.friend.urls')),
    path('users/orientation/', include('users.orientation.urls')),
    

    ### --- Magistrate --- ###
    path("magistrate/", include("magistrate.urls")),
    path("magistrate/tournament/", include("magistrate.tournament.urls")),
    path("magistrate/game/", include("magistrate.game.urls")),
    path("magistrate/match/", include("magistrate.match.urls")),


    ### --- Dominus --- ###
    path("dominus/", include("dominus.urls")),
    path("dominus/team/", include("dominus.team.urls")),
    path("dominus/roster/", include("dominus.roster.urls")),

    ### --- Patronus --- ###

    ### --- Gladiatori --- ###

    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#STATIC FILES IMPORT SOLUTION - NOT WORKING
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += staticfiles_urlpatterns()

#print(urlpatterns)

users/urls.py
from django.urls import path
from django.conf.urls import include
from users import views
# Create your views here.
app_name = "users"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
    path("profile/setup", views.setup_profile, name="profile_setup"),
    path("profile/<int:user_id>/edit", views.updateProfileView.as_view(), name="updateProfileView"),
]

templates/components/form/form_base.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% load l10n %}
{{ form.media }}
<div class="form-container">
    
    <div class="form-header">
        <h2>{% if form_title %}{{form_title}}{% else %}Form{% endif %}</h2>
        {% block form_header %}{% endblock form_header %}
    </div>

    <form method="POST" class="default-form" enctype="multipart/form-data">
        {% csrf_token %}{% comment %} {{form.as_p}} {% endcomment %}
        {% localize on %}
            {{form|crispy}}
        {% endlocalize %}
        {% block form_body %}{% endblock form_body %}
        <input type="submit" value="{% if form_title %}{{form_title}}{% else %}Submit{% endif %}" class="btn btn-outline-success" >
    </form>
    <div class="form-footer">
        {% if previous_page %}<a class="btn btn-outline-dark" href="{{previous_page}}"><b>← </b></a>{% endif %}
        <a class="btn btn-outline-dark" href="{% url 'users:dashboard' %}"><div>Dashboard</div></a>
        {% block form_footer %}{% endblock form_footer %}
    </div>
</div>
{% endblock content %}