core/urls.py
from django.urls import path
from django.conf.urls import include
from core import views
# Create your views here.
app_name = "core"

urlpatterns = [
    path("", views.welcome, name="welcome"),
    path("welcome/", views.welcome, name="welcome"),
    path("home", views.home, name="home"),

    path("components/core/gmm-core/gmm-core-template", views.gmm_core_view, name="gmm_core_view"),
]

dominus/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

# Create your views here.
app_name = "dominus"

urlpatterns = [
    #path("dashboard/", views.dashboard, name="dashboard"),
    #path("accounts/", include("django.contrib.auth.urls")),
    #path("register/", views.register, name="register"),
    #path("profile/setup", views.setup_profile, name="profile_setup"),
    #path("profile/<int:user_id>/edit", views.updateProfileView.as_view(), name="updateProfileView"),
    
    ## --- Organization --- ##
    path("organization/register", views.RegisterOrganizationView.as_view(), name="registerOrganizationView"),
    path("organization/<int:organization_id>/update", views.OrganizationUpdateView.as_view(), name="organizationUpdateView"),
    path("organization/<int:organization_id>/delete", views.OrganizationDeleteView.as_view(), name="organizationDeleteView"),
    path('organization/<int:organization_id>/detail_view', views.OrganizationDetailView.as_view(), name='organizationDetailView'),
    ## --- Organization --- ##



    

]

gladiatorus_server/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    
    ### --- Core --- ###
    path("", include("core.urls")),
    
    ### --- Users --- ###
    path("users/", include("users.urls")),
    path('users/friend/', include('users.friend.urls')),
    path('users/orientation/', include('users.orientation.urls')),
    

    ### --- Magistrate --- ###
    path("magistrate/", include("magistrate.urls")),
    path("magistrate/tournament/", include("magistrate.tournament.urls")),
    path("magistrate/game/", include("magistrate.game.urls")),
    path("magistrate/match/", include("magistrate.match.urls")),


    ### --- Dominus --- ###
    path("dominus/", include("dominus.urls")),
    path("dominus/team/", include("dominus.team.urls")),
    path("dominus/roster/", include("dominus.roster.urls")),

    ### --- Patronus --- ###

    ### --- Gladiatori --- ###

    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#STATIC FILES IMPORT SOLUTION - NOT WORKING
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += staticfiles_urlpatterns()

#print(urlpatterns)

core/views.py
from django.shortcuts import render

# Create your views here.
def welcome(request):
    context = {"page_title":"Welcome"}
    return render(request, "pages/welcome.html", context)


def home(request):
    context = {"page_title":"Welcome"}
    return render(request, "pages/welcome.html", context)


# ############################################
#
# - Core menu Parts
#

def gmm_core_view(request):
    context = {}
    
    #if user isn't logged in
    gmm_core_path = "components/core/gmm-core/gmm-core-template.html"

    #if logged in
    if request.user.is_authenticated:
        gmm_core_path = request.user.userorientation.get_template()

    return render(request, gmm_core_path, context)

templates/components/core/gmm-core/gmm-core-dominus.html
<div class="gmm-core-urls-container" id="gmm-core-urls-container">
    <h2>Forms - Dominus</h2>
    {% for core_urls in orientation.forms %}
        <a class="btn btn-outline" href="{% url "core_urls.link" %}">{{core_urls.name}}</a>
    {% endfor %}
    <a class="btn btn-outline" href="{% url "dominus:registerOrganizationView" %}">Register Organization</a>
    <a class="btn btn-outline" href="{% url "dominus.team:registerTeamView" %}">Register Team</a>
    <h3>Organizations</h3>
    {% for organization in user.owned_organizations.all %}
        {% include "components/dominus/_organization.html" %}
    {% endfor %}

    <h3>Teams</h3>
    {% for team in user.player.teams.all %}  
        {% include "components/dominus/team/_team.html" %}
    {% endfor %}
</div>

{% comment %} Fix teams by looking at the teams in the users organizations {% endcomment %}

templates/components/core/gmm-core/gmm-core-gladiatorus.html
<div class="gmm-core-urls-container" id="gmm-core-urls-container">
    <h2>Forms - Gladiatorus</h2>
    {% for core_urls in orientation.forms %}
        <a class="btn btn-outline" href="{% url "core_urls.link" %}">{{core_urls.name}}</a>
    {% endfor %}
</div>

templates/components/core/gmm-core/gmm-core-magistrate.html
<div class="gmm-core-urls-container" id="gmm-core-urls-container">
    <h2>Forms - Magistrate</h2>
    {% for core_urls in orientation.forms %}
        <a class="btn btn-outline" href="{% url "core_urls.link" %}">{{core_urls.name}}</a>
    {% endfor %}
    <a class="btn btn-outline" href="{% url "magistrate.tournament:registerTournamentView" %}">Register Tournament</a>
    <a class="btn btn-outline" href="{% url "magistrate.game:registerGameView" %}">Register Game</a>
    <a class="btn btn-outline" href="{% url "magistrate.match:registerMatchView" %}">Register Match</a>


    <h3>Registered Tournaments</h3>
    {% for tournament in user.registered_tournaments.all %}
        {% include "components/magistrate/_tournament.html" with tournament=tournament %}
    {% endfor %}

    <br>
    <h3>Registered Matches</h3>
    {% for match in user.registered_matches.all %}
        {% include "components/magistrate/_match.html" with match=match %}
    {% endfor %}
    
    <br>
    {% comment %} <h3>Registered Games</h3>

    {% for game in magistrate.game.game.all %}
        {% include "components/magistrate/_game.html" %}
    {% endfor %} {% endcomment %}
</div>

templates/components/core/gmm-core/gmm-core-template.html
<div class="gmm-core-urls-container" id="gmm-core-urls-container">
    <h2>Forms</h2>
    {% for core_urls in orientation.forms %}
        <a class="btn btn-outline" href="{% url "core_urls.link" %}">{{core_urls.name}}</a>
    {% endfor %}
</div>