core/urls.py
from django.urls import path
from django.conf.urls import include
from core import views
# Create your views here.
app_name = "core"

urlpatterns = [
    path("", views.welcome, name="welcome"),
    path("welcome/", views.welcome, name="welcome"),
    path("home", views.home, name="home"),

    path("components/core/gmm-core/gmm-core-template", views.gmm_core_view, name="gmm_core_view"),
]

dominus/team/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

# Create your views here.
app_name = "dominus.team"

urlpatterns = [
    ## --- Team --- ## Do we move them back? :) 
    path("team/register", views.RegisterTeamView.as_view(), name="registerTeamView"),
    path("team/<int:team_id>/update", views.TeamUpdateView.as_view(), name="teamUpdateView"),
    path("team/<int:team_id>/delete", views.TeamDeleteView.as_view(), name="teamDeleteView"),
    path('team/<int:team_id>/detail_view', views.TeamDetailView.as_view(), name='teamDetailView'),
    
    path("team/<int:team_id>/home", views.team_home, name="team_home"),
    ## --- Team --- ##


    
]

gladiatorus_server/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    
    ### --- Core --- ###
    path("", include("core.urls")),
    
    ### --- Users --- ###
    path("users/", include("users.urls")),
    path('users/friend/', include('users.friend.urls')),
    path('users/orientation/', include('users.orientation.urls')),
    

    ### --- Magistrate --- ###
    path("magistrate/", include("magistrate.urls")),
    path("magistrate/tournament/", include("magistrate.tournament.urls")),
    path("magistrate/game/", include("magistrate.game.urls")),
    path("magistrate/match/", include("magistrate.match.urls")),


    ### --- Dominus --- ###
    path("dominus/", include("dominus.urls")),
    path("dominus/team/", include("dominus.team.urls")),
    path("dominus/roster/", include("dominus.roster.urls")),

    ### --- Patronus --- ###

    ### --- Gladiatori --- ###

    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#STATIC FILES IMPORT SOLUTION - NOT WORKING
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += staticfiles_urlpatterns()

#print(urlpatterns)

users/urls.py
from django.urls import path
from django.conf.urls import include
from users import views
# Create your views here.
app_name = "users"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
    path("profile/setup", views.setup_profile, name="profile_setup"),
    path("profile/<int:user_id>/edit", views.updateProfileView.as_view(), name="updateProfileView"),
]

dominus/team/forms.py
from django.forms import ModelForm, SelectDateWidget, TextInput, widgets
from .models import Team

from datetimewidget.widgets import DateTimeWidget
from crispy_forms.helper import FormHelper

class TeamRegisterForm(ModelForm):
    class Meta:
        model = Team
        fields = ["name", "tag", "members", "logo", "banner", "description", "organization"]

    
    def __init__(self, *args, **kwargs):
        super(TeamRegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)

magistrate/match/forms.py
from django.forms import ModelForm, SelectDateWidget, TextInput, widgets
from .models import Match

from datetimewidget.widgets import DateTimeWidget
from crispy_forms.helper import FormHelper

class MatchRegisterForm(ModelForm):
    class Meta:
        model = Match
        fields = ["time",  "game", "attacker", "defender" ]

        widgets = {
                #Use localization and bootstrap 3
                'time': DateTimeWidget(attrs={'id':"time_id"}, usel10n = True, bootstrap_version=5),
                }
    def __init__(self, *args, **kwargs):
        super(MatchRegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)

dominus/team/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView


from dominus.models import Organization
from .models import Team
from .forms import TeamRegisterForm
# Create your views here.


class RegisterTeamView(LoginRequiredMixin,UserPassesTestMixin, CreateView):
    model = Team
    form_class = TeamRegisterForm
    # def get_object(self, queryset=None):
    #     user = User.objects.get(id=self.kwargs.get("user_id"))
    #     return user.profile
    def test_func(self):
        #Lets check if the user can represent an Team? and has the rights to create a team dominus.team.views line 21
        #Can we check if the banner has actually been uploaded?
        

        return True
    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.registrar = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        # Find your next url here
        next_url = self.request.POST.get("next", None)
        return reverse('users:dashboard')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_page"] = self.request.META.get('HTTP_REFERER')
        context["form_title"] = "Create Team"
        return context

class TeamUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Team
    form_class = TeamRegisterForm
    #template_name = 'path/to/your/update_template.html'

    def get_object(self, queryset=None):
        return Team.objects.get(id=self.kwargs.get("team_id"))

    def test_func(self):
        # Assuming you want only the creator or owners to update the Team
        Team = self.get_object()
        return self.request.user == Team.creator or self.request.user in Team.owners.all()

    def get_success_url(self):
        # Redirect to the detail page of the Team after updating
        #can you look at this next line and correct it so ti goes to the detail view?
        
        return reverse_lazy('dominus.team:teamDetailView', kwargs={'team_id':self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_page"] = self.request.META.get('HTTP_REFERER')
        context["form_title"] = "Update Team"
        return context

class TeamDetailView(DetailView):
    model = Team
    form_class = TeamRegisterForm
    #template_name = 'path/to/your/detail_template.html'  # Specify your template here

    def get_object(self, queryset=None):
        return Team.objects.get(id=self.kwargs.get("team_id"))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # You can add more context if needed
        context["form_title"] = "Team Details"
        context["previous_page"] = self.request.META.get('HTTP_REFERER')
        return context

class TeamDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Team
    #template_name = 'path/to/your/delete_template.html'

    def get_object(self, queryset=None):
        return Team.objects.get(id=self.kwargs.get("team_id"))
    def test_func(self):
        # Assuming you want only the creator to delete the Team
        return self.request.user == self.get_object().creator

    def get_success_url(self):
        # Redirect to a safe page, like user dashboard, after deletion
        return reverse_lazy('users:dashboard')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_page"] = self.request.META.get('HTTP_REFERER')
        context["form_title"] = "Delete Team"
        return context
    
def team_home(request, team_id):
    team = get_object_or_404(Team, id=team_id)
    context = {
        'team': team,
        'form_title': 'Team Details',
        'previous_page': request.META.get('HTTP_REFERER'),
    }
    return render(request, 'team/team_app.html', context)

magistrate/match/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.models import User
from django.urls import reverse_lazy

from .models import Match
from .forms import MatchRegisterForm
from magistrate.tournament.models import TournamentMatch

# Create your views here.
class RegisterMatchView(LoginRequiredMixin,UserPassesTestMixin, CreateView):
    model = Match
    form_class = MatchRegisterForm
    # def get_object(self, queryset=None):
    #     user = User.objects.get(id=self.kwargs.get("user_id"))
    #     return user.profile
    def test_func(self):
        #Lets check if the user can represent an Match? and has the rights to create a match magistrate.match.views line 21
        return True
    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.instance.registrar = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        # Find your next url here
        next_url = self.request.POST.get("next", None)
        return reverse('users:dashboard')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_page"] = self.request.META.get('HTTP_REFERER')
        context["form_title"] = "Create Match"
        return context


#Can we have this class check if the match is a tournament match or a standalone match?
# If it is a tournament match, let's include the tournament match model
# If it is a standalone match, let's include the standalone match model

class MatchUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Match
    form_class = MatchRegisterForm
    #template_name = 'path/to/your/update_template.html'

    def get_object(self, queryset=None):
        return Match.objects.get(id=self.kwargs.get("match_id"))

    def test_func(self):
        # Assuming you want only the creator or owners to update the Match
        Match = self.get_object()
        return self.request.user == Match.creator or self.request.user in Match.owners.all()

    def get_success_url(self):
        # Redirect to the detail page of the Match after updating
        #can you look at this next line and correct it so ti goes to the detail view?
        
        return reverse_lazy('magistrate.match:matchDetailView', kwargs={'match_id': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_page"] = self.request.META.get('HTTP_REFERER')
        context["form_title"] = "Update Match"
        return context

class MatchDetailView(DetailView):
    model = Match
    form_class = MatchRegisterForm
    #template_name = 'path/to/your/detail_template.html'  # Specify your template here

    def get_object(self, queryset=None):
        return Match.objects.get(id=self.kwargs.get("match_id"))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # You can add more context if needed
        context["form_title"] = "Match Details"
        context["previous_page"] = self.request.META.get('HTTP_REFERER')
        return context

class MatchDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Match
    #template_name = 'path/to/your/delete_template.html'

    def get_object(self, queryset=None):
        return Match.objects.get(id=self.kwargs.get("match_id"))
    def test_func(self):
        # Assuming you want only the creator to delete the Match
        return self.request.user == self.get_object().creator

    def get_success_url(self):
        # Redirect to a safe page, like user dashboard, after deletion
        return reverse_lazy('users:dashboard')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["previous_page"] = self.request.META.get('HTTP_REFERER')
        context["form_title"] = "Delete Match"
        return context
    
def match_home(request, match_id):
    try:
        match = Match.objects.get(id=match_id)
    except Match.DoesNotExist:
        match = None
    
    try:
        tournamentMatch = TournamentMatch.objects.get(id=match_id)
        match = tournamentMatch
    except TournamentMatch.DoesNotExist:
        tournamentMatch = None
    print(tournamentMatch)
    
    if tournamentMatch:
        pass
        #match = tournamentMatch
    
    description = match.attacker.name + " vs " + match.defender.name + " - " + str(match.time) + " - " + match.game.name    
    context = {
        'page_title': 'Match: ' + match.attacker.tag + " vs " + match.defender.tag  + " - " + str(match.time) + " - " + match.game.name,
        'page_header': 'Tournament',
        'page_description': description,

        'match': match,
        #'tournament' = tour
        
        'form_title': 'Match Details',
        'previous_page': request.META.get('HTTP_REFERER'),
    }
    return render(request, 'match/match_app.html', context)

users/friend/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import FriendRequest, Friendship
from django.contrib.auth.models import User
from users.models import Profile

# Create your views here.

@login_required
def send_friend_request(request, profile_uuid):
    if request.method == 'POST':
        receiver = get_object_or_404(User, uuid=profile_uuid)
        if FriendRequest.objects.filter(sender=request.user.profile, receiver=receiver).exists() or \
                Friendship.objects.filter(user1=request.user.profile, user2=receiver).exists() or \
                Friendship.objects.filter(user1=receiver, user2=request.user.profile).exists():
            messages.error(request, 'Friend request already sent or you are already friends.')
            return redirect('friend:list_friends')
        
        FriendRequest(sender=request.user, receiver=receiver).save()
        messages.success(request, 'Friend request sent.')
    return redirect('friend:list_friends')

@login_required
def accept_friend_request(request, request_id):
    if request.method == 'POST':
        friend_request = get_object_or_404(FriendRequest, id=request_id)
        if friend_request.receiver == request.user:
            Friendship(user1=friend_request.sender, user2=request.user).save()
            friend_request.delete()
            messages.success(request, 'Friend request accepted.')
        else:
            messages.error(request, 'Invalid request.')
    return redirect('friend:list_pending_requests')

# Similar implementations can be done for decline_friend_request, remove_friend, list_friends, and list_pending_requests views.

users/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.models import User

from users.forms import CustomUserCreationForm, ProfileEditForm

from .models import Profile


def dashboard(request):
    context = {"page_title":"Bruker"}
    return render(request, "users/dashboard.html", context)

def register(request):
    if request.method =="GET":
        return render(
            request, "users/register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            print("GODKJENT")
            return redirect(reverse("users:dashboard"))
        else:
            #print(form.errors)
            print("AVKREFTET - bug i register funksjon")
            return render(
            request, "users/register.html",
            {"form": form}
        )

def setup_profile(request):
    form = True
    if request.method =="GET":
        return render(request, "users/profile_setup.html", {"form":form})
    elif request.method =="POST":
        if form: #form.is_valid
            return redirect(reverse("users:dashboard"))
        else:
            return render(request, "users/profile_setup.html", {"form":form})





class updateProfileView(LoginRequiredMixin,UserPassesTestMixin, UpdateView):
    model = Profile
    form_class = ProfileEditForm
    def get_object(self, queryset=None):
        user = User.objects.get(id=self.kwargs.get("user_id"))
        return user.profile
    def test_func(self):
        profile = self.get_object(self)
        if self.request.user.id == profile.user.id:
            return True
        print("FALSE")
        return False
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        # Find your next url here
        next_url = self.request.POST.get("next", None)
        return reverse('users:dashboard')

users/templates/users/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- /templates/users/dashboard.html -->
<div class="default-bodycontainer">
    <div class="dashboard">
        <div class="dashboard-header">
            <h1>Hello, {{ user.username|default:'Guest' }}!</h1>
            <!--default user icon-->
            
            {% if user.is_authenticated %}
                <img class="dashboard-header-user-icon-img" src="{{user.profile.profileImage.url}}" alt="user-profile-image">
            {% else %}
                <img class="dashboard-header-user-icon-img" src="{% static 'gladiatorus-base/img/icons/user-related/user-not-authenticated_400.png' %}" alt="user-profile-image">
            {% endif %}
        </div>
        <br>
        <div class="dashboard-content">
            {% if user.is_authenticated %}
                <h1>{{user.username}}</h1>
            {% else %}
            
                <p><i>Du har ikke en bruker hos oss :&#41; Det er helt greit &#60;3 </i></p>
                <br>
                <p><b>NB!</b> Du kan fortsatt bruke alle tjenestene våre</p>
                <br>
                <br>
                <p>Vårt mål med plattformen er å sørge for å ivareta en bit av befolkningen vår som 
                    per dags status blir utelatt og diskriminert mot. Derfor kan alle uansett hvem, hva eller fra hvor;
                    bruke plattformen &#40;uten å måtte logge seg inn.&#41;
                    
                    Om man skulle ønske å logge seg inn, er det heller ikke et behov å gi riktig opplysninger, og mail er kun dersom man vil gjennopprette brukeren sin ved feil.
                </p>
                <br>
                <p>Uansett, vi er glade for at du er her og håper du får nytte av tjenesten vi har laget</p>
                <br>
                <p> her er en link til en forklaringsside: </p>
                {% comment %} <br><p> Her er link til kartet: <a href="{% url 'web_app:welcome_view' %}">Forsiden</a></p> {% endcomment %}
                <br>
                <p>Med de vennligste hilsner: <b>Neo Caesar</b></p>
            {% endif %}
        </div>
        <div class="dashboard-utility-bar">
            {% if user.is_authenticated %}
                
                <a class="btn btn-outline-success" href="{% url 'users:updateProfileView' user_id=user.id %}">Edit Profile</a>
                <a class="btn btn-outline-warning" href="{% url 'logout' %}">Logout</a>
                <a class="btn btn-outline-danger" href="{% url 'password_change' %}">Change password</a>
                <div>
                    
                </div>
            {% else %}
                <a class="btn btn-outline-success" href="{% url 'login' %}">Login</a>
                <a class="btn btn-outline-primary" href="{% url 'users:register' %}" ><div>Register</div></a>
            {% endif %}
        </div>

        <div>
            {% comment %} <button onclick="WriteToFile()">get settings.txt</button> {% endcomment %}

        </div>
    </div>
</div>

<style>
body{
    color:#6b6b6b;
}
.dashboard a{
    margin:10px;
}
.default-bodycontainer{
    height:100%;
    width: 100%;
}
.dashboard{
    height:100%;
    width: 100%;
    padding-left: 10px;

    padding-right: 10px;
}

.dashboard-header{
    display: flex;
    justify-content: space-around;
    align-items: center;
}
.dashboard-header img{
    width: 100px;
}

.dashboard-content{
    display: flex;
    flex-direction: column;
    align-content: center;
    align-items: center;
}
.dashboard-utility-bar{

}
</style>



<script>
    
    {% if user.is_authenticated %}
    let user_name = "{{user.username}}";
    console.log("User ["+user_name+"] - Authenticated")
    {% endif %}
    
</script>



{% endblock content %}

users/templates/users/leagueoflegendsroster_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class = "container">
    <div class="formContainer">
        <form method="POST" enctype="multipart/form-data" class="default-form">
            {% csrf_token %}
            <h1> Create Roster </h1>

            {{ form|crispy }}

            <button class="btn btn-outline-info publish-ad-btn">
                Save Team
            </button>
        </form>
        {{ form.media.js }}
    </div>
    {% include "modules/_findPlayerModule.html" %}
    {% if previous_page %}
        <a class="btn btn-outline-info" href="{{previous_page}}">Back</a>
    {% endif %}
</div>


{% endblock content %}

users/templates/users/location_interest_form.html
{extends "single_body.html"}

{block content}

<form method="POST">
    {% csrf_token %}
    {{form}}

    
    <input type="submit" value="Register">
</form>

{endblock content}

users/templates/users/match_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<head>
</head>
<div class = "container">
    
        <form method="POST" enctype="multipart/form-data" class="default-form">
            {% csrf_token %}
            <h1> Are you sure you want to delete the match? </h1>
            <br>
            <h4>{{object.team1.name}} - {{object.team2.name}}</h4>
            <br>
            <h4>{{object.liga.name}}</h4>
            <br>
            <h4>{{object.time}}</h4>
        

            <button class="btn btn-outline-danger publish-ad-btn" type="submit">
                DELETE Match
            </button>
            <a class="btn btn-outline-secondary publish-ad-btn" href="{% url 'streaming:viewControlboard' match_id=object.id %}">
                Cancel
            </a>
            {% if previous_page %}
                <a class="btn btn-outline-info" href="{{previous_page}}">Back</a>
            {% endif %}
        </form>
    
</div>

{% endblock content %}

users/templates/users/match_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<head>
{{ form.media }}
{% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
</head> {% endcomment %}
<div class = "container">
    
        <form method="POST" enctype="multipart/form-data" class="default-form">
            {% csrf_token %}
            <h1> Create Match </h1>

            {{ form|crispy }}
            {% comment %} {{ form.as_table }} {% endcomment %}

            <button class="btn btn-outline-info publish-ad-btn">
                Save Match
            </button>
            <a class="btn btn-outline-secondary publish-ad-btn" href="{% url 'streaming:home' %}">
                Cancel
            </a>
            {% if previous_page %}
                <a class="btn btn-outline-info" href="{{previous_page}}">Back</a>
            {% endif %}
        </form>
    
</div>

{% endblock content %}

users/templates/users/player_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<head>
{{ form.media }}
{% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
</head> {% endcomment %}
<div class = "container">
    
        <form method="POST" enctype="multipart/form-data" class="default-form">
            {% csrf_token %}
            <h1> New Player </h1>

            {{ form|crispy }}
            {% comment %} {{ form.as_table }} {% endcomment %}

            <button class="btn btn-outline-info publish-ad-btn">
                Save Player
            </button>
            <a class="btn btn-outline-secondary publish-ad-btn" href="{% url 'streaming:home' %}">
                Cancel
            </a>
            {% if previous_page %}
                <a class="btn btn-outline-info" href="{{previous_page}}">Back</a>
            {% endif %}
        </form>
    
</div>

{% endblock content %}

users/templates/users/profile_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<head>
{{ form.media }}
{% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
</head> {% endcomment %}
<div class="form-container">
<div class = "container">
    
        <form method="POST" enctype="multipart/form-data" class="default-form">
            {% csrf_token %}
            <h1> Your Profile </h1>

            {{ form|crispy }}
            {% comment %} {{ form.as_table }} {% endcomment %}

            <button class="btn btn-outline-info publish-ad-btn">
                Save changes
            </button>
            {% if previous_page %}
                <a class="btn btn-outline-info" href="{{previous_page}}">Back</a>
            {% endif %}
        </form>
    
</div>
</div>

{% endblock content %}

users/templates/users/register.html
<!--hovedisde/templates/users/register.html-->

{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="form-container">

    <div class="form-header">
        <h2>Register</h2>
    </div>

    <form method="post" class="form default-form">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Register" class="btn btn-outline-success">
    </form>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
    <div class="form-footer">
        <a class="btn btn-outline-primary" href="{% url 'login' %}">Back to login</a>
    </div>
</div>
    <style>
        body{
            {% comment %} color:white;
            color: black; {% endcomment %}
        }
        form{
            display: inline-grid;
            padding: 15px;
        }
    </style>
{% endblock content %}

users/templates/users/team_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class = "container">
    
        <form method="POST" enctype="multipart/form-data" class="default-form">
            {% csrf_token %}
            <h1> Create Team </h1>

            {{ form|crispy }}

            <button class="btn btn-outline-info publish-ad-btn">
                Save Team
            </button>
        </form>

        <div class="rosters" style="color:white;">
            {% if object.leagueOfLegendsRosters %}
                {% if object.leagueOfLegendsRosters.all.0 %}
                {% comment %} {{object.leagueOfLegendsRosters.all}} {% endcomment %}
                    {% for rosters in object.leagueOfLegendsRosters.all %}
                    <a class="btn btn-outline-info" href="{% url 'streaming:update-LOL-RosterView' pk=object.leagueOfLegendsRosters.all.0.id %}">Edit {{roster.name}}</a>
                    {{roster.id}}
                    
                    {% endfor %}
                    {% comment %} <a class="btn btn-outline-info" href="{% url 'streaming:update-LOL-RosterView' pk=object.leagueOfLegendsRosters.all.0.id %}">Edit {{roster.name}}</a> {% endcomment %}
                {% else %}
                    <a class="btn btn-outline-info" href="{% url 'streaming:createLeagueOfLegendsRoster' %}">Add Roster</a>
                {% endif %}
                <a class="btn btn-outline-info" href="{% url 'streaming:createLeagueOfLegendsRoster' %}">Add Another Roster</a>
            {% else %}
                <a class="btn btn-outline-info" href="{% url 'streaming:createLeagueOfLegendsRoster' %}">Add Roster</a>
            {% endif %}
            {% if previous_page %}
                <a class="btn btn-outline-info" href="{{previous_page}}">Back</a>
            {% endif %}
        </div>

        
    
</div>

{% endblock content %}